name: docker-compose-actions-workflow
on: push
jobs:
  build:
    runs-on: nwl-temp
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: docker-compose up --force-recreate --build --detach
